name: CI

on:
  push:
  pull_request:

jobs:
  cargo-udeps:
    strategy:
      fail-fast: false
      matrix:
        target-triple:
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
        nightly-channel:
          - nightly-2021-09-16
          - nightly-2021-10-02
        cargo-http-multiplexing:
          - 'false'
          - 'true'
        include:
          - { target-triple: x86_64-pc-windows-msvc  , os: windows-2019, nightly-channel: nightly-2021-09-16, cargo-http-multiplexing: 'false' }
          - { target-triple: x86_64-pc-windows-msvc  , os: windows-2019, nightly-channel: nightly-2021-09-16, cargo-http-multiplexing: 'true'  }
          - { target-triple: x86_64-pc-windows-msvc  , os: windows-2019, nightly-channel: nightly-2021-10-02, cargo-http-multiplexing: 'false' }
          - { target-triple: x86_64-pc-windows-msvc  , os: windows-2019, nightly-channel: nightly-2021-10-02, cargo-http-multiplexing: 'true'  }
          - { target-triple: x86_64-apple-darwin     , os: macos-10.15 , nightly-channel: nightly-2021-09-16, cargo-http-multiplexing: 'false' }
          - { target-triple: x86_64-apple-darwin     , os: macos-10.15 , nightly-channel: nightly-2021-09-16, cargo-http-multiplexing: 'true'  }
          - { target-triple: x86_64-apple-darwin     , os: macos-10.15 , nightly-channel: nightly-2021-10-02, cargo-http-multiplexing: 'false' }
          - { target-triple: x86_64-apple-darwin     , os: macos-10.15 , nightly-channel: nightly-2021-10-02, cargo-http-multiplexing: 'true'  }
          - { target-triple: x86_64-unknown-linux-gnu, os: ubuntu-20.04, nightly-channel: nightly-2021-09-16, cargo-http-multiplexing: 'false' }
          - { target-triple: x86_64-unknown-linux-gnu, os: ubuntu-20.04, nightly-channel: nightly-2021-09-16, cargo-http-multiplexing: 'true'  }
          - { target-triple: x86_64-unknown-linux-gnu, os: ubuntu-20.04, nightly-channel: nightly-2021-10-02, cargo-http-multiplexing: 'false' }
          - { target-triple: x86_64-unknown-linux-gnu, os: ubuntu-20.04, nightly-channel: nightly-2021-10-02, cargo-http-multiplexing: 'true'  }

    name: ${{ matrix.target-triple }}, ${{ matrix.nightly-channel }}, $CARGO_HTTP_MULTIPLEXING=${{ matrix.cargo-http-multiplexing }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up `stable`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Set up `${{ matrix.nightly-channel }}`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.nightly-channel }}
          profile: minimal

      - name: Install cargo-udeps v0.1.23
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: install
          args: cargo-udeps --version =0.1.23 --locked

      - name: Run cargo-udeps
        run: |
          cat >./Cargo.toml <<EOF
          [package]
          name = "investigate-curl-error-on-cargo"
          version = "0.0.0"
          edition = "2018"

          [lib]
          path = "/dev/null"

          [dependencies]
          reqwest = "0.11.4"
          EOF

          cargo +${{ matrix.nightly-channel }} udeps || true
        shell: bash
        env:
          CARGO_HTTP_MULTIPLEXING: ${{ matrix.cargo-http-multiplexing }}
